# Generated by Django 3.1.5 on 2021-01-17 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 13, 4, 16, 69460, tzinfo=utc), null=True),
        ),
    ]
