# Generated by Django 3.1.5 on 2021-01-17 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_reviews', '0005_auto_20210117_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 17, 14, 46, 48, 261385, tzinfo=utc), null=True),
        ),
    ]
